package com.example.chatto.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006973)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9EF0FC)
val onPrimaryContainerLight = Color(0xFF001F23)
val secondaryLight = Color(0xFF4A6266)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCDE7EC)
val onSecondaryContainerLight = Color(0xFF051F22)
val tertiaryLight = Color(0xFF525E7D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD9E2FF)
val onTertiaryContainerLight = Color(0xFF0D1B37)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FAFB)
val onBackgroundLight = Color(0xFF171D1E)
val surfaceLight = Color(0xFFF5FAFB)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFDBE4E6)
val onSurfaceVariantLight = Color(0xFF3F484A)
val outlineLight = Color(0xFF6F797A)
val outlineVariantLight = Color(0xFFBFC8CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3132)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFF81D3DF)

val primaryLightMediumContrast = Color(0xFF004A52)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF24808B)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF2F474A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF60797D)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF364260)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF687495)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF5FAFB)
val onBackgroundLightMediumContrast = Color(0xFF171D1E)
val surfaceLightMediumContrast = Color(0xFFF5FAFB)
val onSurfaceLightMediumContrast = Color(0xFF171D1E)
val surfaceVariantLightMediumContrast = Color(0xFFDBE4E6)
val onSurfaceVariantLightMediumContrast = Color(0xFF3B4446)
val outlineLightMediumContrast = Color(0xFF576162)
val outlineVariantLightMediumContrast = Color(0xFF737C7E)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3132)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F3)
val inversePrimaryLightMediumContrast = Color(0xFF81D3DF)

val primaryLightHighContrast = Color(0xFF00272B)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004A52)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF0C2629)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF2F474A)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF14213E)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF364260)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF5FAFB)
val onBackgroundLightHighContrast = Color(0xFF171D1E)
val surfaceLightHighContrast = Color(0xFFF5FAFB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDBE4E6)
val onSurfaceVariantLightHighContrast = Color(0xFF1C2527)
val outlineLightHighContrast = Color(0xFF3B4446)
val outlineVariantLightHighContrast = Color(0xFF3B4446)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B3132)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFBCF6FF)

val primaryDark = Color(0xFF81D3DF)
val onPrimaryDark = Color(0xFF00363C)
val primaryContainerDark = Color(0xFF004F57)
val onPrimaryContainerDark = Color(0xFF9EF0FC)
val secondaryDark = Color(0xFFB1CBCF)
val onSecondaryDark = Color(0xFF1C3438)
val secondaryContainerDark = Color(0xFF334B4E)
val onSecondaryContainerDark = Color(0xFFCDE7EC)
val tertiaryDark = Color(0xFFB9C6EA)
val onTertiaryDark = Color(0xFF23304D)
val tertiaryContainerDark = Color(0xFF3A4664)
val onTertiaryContainerDark = Color(0xFFD9E2FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1415)
val onBackgroundDark = Color(0xFFDEE3E4)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDEE3E4)
val surfaceVariantDark = Color(0xFF3F484A)
val onSurfaceVariantDark = Color(0xFFBFC8CA)
val outlineDark = Color(0xFF899294)
val outlineVariantDark = Color(0xFF3F484A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E4)
val inverseOnSurfaceDark = Color(0xFF2B3132)
val inversePrimaryDark = Color(0xFF006973)

val primaryDarkMediumContrast = Color(0xFF86D7E4)
val onPrimaryDarkMediumContrast = Color(0xFF001A1D)
val primaryContainerDarkMediumContrast = Color(0xFF489CA8)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFB5CFD4)
val onSecondaryDarkMediumContrast = Color(0xFF011A1D)
val secondaryContainerDarkMediumContrast = Color(0xFF7C9599)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFBECAEF)
val onTertiaryDarkMediumContrast = Color(0xFF071531)
val tertiaryContainerDarkMediumContrast = Color(0xFF8490B2)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0E1415)
val onBackgroundDarkMediumContrast = Color(0xFFDEE3E4)
val surfaceDarkMediumContrast = Color(0xFF0E1415)
val onSurfaceDarkMediumContrast = Color(0xFFF6FCFD)
val surfaceVariantDarkMediumContrast = Color(0xFF3F484A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC3CCCE)
val outlineDarkMediumContrast = Color(0xFF9BA5A6)
val outlineVariantDarkMediumContrast = Color(0xFF7B8586)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE3E4)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2C)
val inversePrimaryDarkMediumContrast = Color(0xFF005058)


val primaryDarkHighContrast = Color(0xFFF1FDFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF86D7E4)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFF1FDFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB5CFD4)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFCFAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFBECAEF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF0E1415)
val onBackgroundDarkHighContrast = Color(0xFFDEE3E4)
val surfaceDarkHighContrast = Color(0xFF0E1415)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3F484A)
val onSurfaceVariantDarkHighContrast = Color(0xFFF3FCFE)
val outlineDarkHighContrast = Color(0xFFC3CCCE)
val outlineVariantDarkHighContrast = Color(0xFFC3CCCE)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF002F35)








